// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: ServiceProto.proto

package Services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_R_NONE Role = 0
	Role_ADMIN  Role = 1
	Role_WORKER Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "R_NONE",
		1: "ADMIN",
		2: "WORKER",
	}
	Role_value = map[string]int32{
		"R_NONE": 0,
		"ADMIN":  1,
		"WORKER": 2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_ServiceProto_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_ServiceProto_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{0}
}

type BookSaleStatus int32

const (
	BookSaleStatus_CLOSE BookSaleStatus = 0
	BookSaleStatus_START BookSaleStatus = 1
)

// Enum value maps for BookSaleStatus.
var (
	BookSaleStatus_name = map[int32]string{
		0: "CLOSE",
		1: "START",
	}
	BookSaleStatus_value = map[string]int32{
		"CLOSE": 0,
		"START": 1,
	}
)

func (x BookSaleStatus) Enum() *BookSaleStatus {
	p := new(BookSaleStatus)
	*p = x
	return p
}

func (x BookSaleStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BookSaleStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_ServiceProto_proto_enumTypes[1].Descriptor()
}

func (BookSaleStatus) Type() protoreflect.EnumType {
	return &file_ServiceProto_proto_enumTypes[1]
}

func (x BookSaleStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BookSaleStatus.Descriptor instead.
func (BookSaleStatus) EnumDescriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{1}
}

type BookInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// isbn号码
	Isbn string `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	// 作者
	Author string `protobuf:"bytes,2,opt,name=author,proto3" json:"author,omitempty"`
	// 作者国籍
	Nation string `protobuf:"bytes,3,opt,name=nation,proto3" json:"nation,omitempty"`
	// 书名
	BookName string `protobuf:"bytes,4,opt,name=book_name,json=bookName,proto3" json:"book_name,omitempty"`
	// 书籍数量
	BookNum uint64 `protobuf:"varint,5,opt,name=book_num,json=bookNum,proto3" json:"book_num,omitempty"`
	// 售卖状态
	Status BookSaleStatus `protobuf:"varint,6,opt,name=status,proto3,enum=Services.BookSaleStatus" json:"status,omitempty"`
	// 数据类型
	BookType string `protobuf:"bytes,7,opt,name=BookType,proto3" json:"BookType,omitempty"`
}

func (x *BookInfo) Reset() {
	*x = BookInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookInfo) ProtoMessage() {}

func (x *BookInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookInfo.ProtoReflect.Descriptor instead.
func (*BookInfo) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{0}
}

func (x *BookInfo) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *BookInfo) GetAuthor() string {
	if x != nil {
		return x.Author
	}
	return ""
}

func (x *BookInfo) GetNation() string {
	if x != nil {
		return x.Nation
	}
	return ""
}

func (x *BookInfo) GetBookName() string {
	if x != nil {
		return x.BookName
	}
	return ""
}

func (x *BookInfo) GetBookNum() uint64 {
	if x != nil {
		return x.BookNum
	}
	return 0
}

func (x *BookInfo) GetStatus() BookSaleStatus {
	if x != nil {
		return x.Status
	}
	return BookSaleStatus_CLOSE
}

func (x *BookInfo) GetBookType() string {
	if x != nil {
		return x.BookType
	}
	return ""
}

type AuthorInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name   string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Nation string `protobuf:"bytes,2,opt,name=nation,proto3" json:"nation,omitempty"`
}

func (x *AuthorInfo) Reset() {
	*x = AuthorInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorInfo) ProtoMessage() {}

func (x *AuthorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorInfo.ProtoReflect.Descriptor instead.
func (*AuthorInfo) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthorInfo) GetNation() string {
	if x != nil {
		return x.Nation
	}
	return ""
}

// admin 接口
// 添加书籍库存
type AddBookNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ISBN   string `protobuf:"bytes,1,opt,name=ISBN,proto3" json:"ISBN,omitempty"`
	AddNum uint64 `protobuf:"varint,2,opt,name=add_num,json=addNum,proto3" json:"add_num,omitempty"`
}

func (x *AddBookNumRequest) Reset() {
	*x = AddBookNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBookNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBookNumRequest) ProtoMessage() {}

func (x *AddBookNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBookNumRequest.ProtoReflect.Descriptor instead.
func (*AddBookNumRequest) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{2}
}

func (x *AddBookNumRequest) GetISBN() string {
	if x != nil {
		return x.ISBN
	}
	return ""
}

func (x *AddBookNumRequest) GetAddNum() uint64 {
	if x != nil {
		return x.AddNum
	}
	return 0
}

type AddBookNumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ErrorInfo string `protobuf:"bytes,2,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
}

func (x *AddBookNumResponse) Reset() {
	*x = AddBookNumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBookNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBookNumResponse) ProtoMessage() {}

func (x *AddBookNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBookNumResponse.ProtoReflect.Descriptor instead.
func (*AddBookNumResponse) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{3}
}

func (x *AddBookNumResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *AddBookNumResponse) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

// 添加新书
type AddNewBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookInfo *BookInfo `protobuf:"bytes,1,opt,name=book_info,json=bookInfo,proto3" json:"book_info,omitempty"`
	Num      uint64    `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *AddNewBookRequest) Reset() {
	*x = AddNewBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNewBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewBookRequest) ProtoMessage() {}

func (x *AddNewBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewBookRequest.ProtoReflect.Descriptor instead.
func (*AddNewBookRequest) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{4}
}

func (x *AddNewBookRequest) GetBookInfo() *BookInfo {
	if x != nil {
		return x.BookInfo
	}
	return nil
}

func (x *AddNewBookRequest) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type AddNewBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ErrorInfo string `protobuf:"bytes,2,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
}

func (x *AddNewBookResponse) Reset() {
	*x = AddNewBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNewBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewBookResponse) ProtoMessage() {}

func (x *AddNewBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewBookResponse.ProtoReflect.Descriptor instead.
func (*AddNewBookResponse) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{5}
}

func (x *AddNewBookResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *AddNewBookResponse) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

// 打开或者关闭书籍售卖
type BookSaleRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Isbn      string `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	SetStatus int32  `protobuf:"varint,2,opt,name=set_status,json=setStatus,proto3" json:"set_status,omitempty"`
}

func (x *BookSaleRequest) Reset() {
	*x = BookSaleRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookSaleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSaleRequest) ProtoMessage() {}

func (x *BookSaleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSaleRequest.ProtoReflect.Descriptor instead.
func (*BookSaleRequest) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{6}
}

func (x *BookSaleRequest) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *BookSaleRequest) GetSetStatus() int32 {
	if x != nil {
		return x.SetStatus
	}
	return 0
}

type BookSaleResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ErrorInfo string `protobuf:"bytes,2,opt,name=ErrorInfo,proto3" json:"ErrorInfo,omitempty"`
}

func (x *BookSaleResponse) Reset() {
	*x = BookSaleResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BookSaleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BookSaleResponse) ProtoMessage() {}

func (x *BookSaleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BookSaleResponse.ProtoReflect.Descriptor instead.
func (*BookSaleResponse) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{7}
}

func (x *BookSaleResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *BookSaleResponse) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

// 减少书籍库存
type DecBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ISBN   string `protobuf:"bytes,1,opt,name=ISBN,proto3" json:"ISBN,omitempty"`
	DecNum uint64 `protobuf:"varint,2,opt,name=dec_num,json=decNum,proto3" json:"dec_num,omitempty"`
}

func (x *DecBookRequest) Reset() {
	*x = DecBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecBookRequest) ProtoMessage() {}

func (x *DecBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecBookRequest.ProtoReflect.Descriptor instead.
func (*DecBookRequest) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{8}
}

func (x *DecBookRequest) GetISBN() string {
	if x != nil {
		return x.ISBN
	}
	return ""
}

func (x *DecBookRequest) GetDecNum() uint64 {
	if x != nil {
		return x.DecNum
	}
	return 0
}

type DecBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ErrorInfo string `protobuf:"bytes,2,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
}

func (x *DecBookResponse) Reset() {
	*x = DecBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecBookResponse) ProtoMessage() {}

func (x *DecBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecBookResponse.ProtoReflect.Descriptor instead.
func (*DecBookResponse) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{9}
}

func (x *DecBookResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *DecBookResponse) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

// 删除书籍
type RemoveBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ISBN string `protobuf:"bytes,1,opt,name=ISBN,proto3" json:"ISBN,omitempty"`
}

func (x *RemoveBookRequest) Reset() {
	*x = RemoveBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBookRequest) ProtoMessage() {}

func (x *RemoveBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBookRequest.ProtoReflect.Descriptor instead.
func (*RemoveBookRequest) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{10}
}

func (x *RemoveBookRequest) GetISBN() string {
	if x != nil {
		return x.ISBN
	}
	return ""
}

type RemoveBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ErrorInfo string `protobuf:"bytes,2,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
}

func (x *RemoveBookResponse) Reset() {
	*x = RemoveBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBookResponse) ProtoMessage() {}

func (x *RemoveBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBookResponse.ProtoReflect.Descriptor instead.
func (*RemoveBookResponse) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveBookResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *RemoveBookResponse) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

// 查询所有书籍数量
type GetAllBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllBookRequest) Reset() {
	*x = GetAllBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBookRequest) ProtoMessage() {}

func (x *GetAllBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBookRequest.ProtoReflect.Descriptor instead.
func (*GetAllBookRequest) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{12}
}

type GetAllBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       int32       `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ErrorInfo string      `protobuf:"bytes,2,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
	BookList  []*BookInfo `protobuf:"bytes,3,rep,name=book_list,json=bookList,proto3" json:"book_list,omitempty"`
}

func (x *GetAllBookResponse) Reset() {
	*x = GetAllBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBookResponse) ProtoMessage() {}

func (x *GetAllBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBookResponse.ProtoReflect.Descriptor instead.
func (*GetAllBookResponse) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{13}
}

func (x *GetAllBookResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *GetAllBookResponse) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

func (x *GetAllBookResponse) GetBookList() []*BookInfo {
	if x != nil {
		return x.BookList
	}
	return nil
}

// 查询单个书籍信息
type GetSingleBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetSingleBookRequest) Reset() {
	*x = GetSingleBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSingleBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleBookRequest) ProtoMessage() {}

func (x *GetSingleBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleBookRequest.ProtoReflect.Descriptor instead.
func (*GetSingleBookRequest) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{14}
}

type GetSingleBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       int32       `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ErrorInfo string      `protobuf:"bytes,2,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
	BookList  []*BookInfo `protobuf:"bytes,3,rep,name=book_list,json=bookList,proto3" json:"book_list,omitempty"`
}

func (x *GetSingleBookResponse) Reset() {
	*x = GetSingleBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetSingleBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSingleBookResponse) ProtoMessage() {}

func (x *GetSingleBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSingleBookResponse.ProtoReflect.Descriptor instead.
func (*GetSingleBookResponse) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{15}
}

func (x *GetSingleBookResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *GetSingleBookResponse) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

func (x *GetSingleBookResponse) GetBookList() []*BookInfo {
	if x != nil {
		return x.BookList
	}
	return nil
}

// 查询书籍数量
type GetBookNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Isbn string `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
}

func (x *GetBookNumRequest) Reset() {
	*x = GetBookNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookNumRequest) ProtoMessage() {}

func (x *GetBookNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookNumRequest.ProtoReflect.Descriptor instead.
func (*GetBookNumRequest) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{16}
}

func (x *GetBookNumRequest) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

type GetBookNumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Num       uint32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	ErrorInfo string `protobuf:"bytes,3,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
}

func (x *GetBookNumResponse) Reset() {
	*x = GetBookNumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookNumResponse) ProtoMessage() {}

func (x *GetBookNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookNumResponse.ProtoReflect.Descriptor instead.
func (*GetBookNumResponse) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{17}
}

func (x *GetBookNumResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *GetBookNumResponse) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *GetBookNumResponse) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

// 购买书籍
type BuyBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BookList []*BuyBookInfo `protobuf:"bytes,1,rep,name=book_list,json=bookList,proto3" json:"book_list,omitempty"`
}

func (x *BuyBookRequest) Reset() {
	*x = BuyBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyBookRequest) ProtoMessage() {}

func (x *BuyBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyBookRequest.ProtoReflect.Descriptor instead.
func (*BuyBookRequest) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{18}
}

func (x *BuyBookRequest) GetBookList() []*BuyBookInfo {
	if x != nil {
		return x.BookList
	}
	return nil
}

type BuyBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       int32          `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Num       uint32         `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	ErrorInfo string         `protobuf:"bytes,3,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
	BookList  []*BuyBookInfo `protobuf:"bytes,4,rep,name=book_list,json=bookList,proto3" json:"book_list,omitempty"`
}

func (x *BuyBookResponse) Reset() {
	*x = BuyBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyBookResponse) ProtoMessage() {}

func (x *BuyBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyBookResponse.ProtoReflect.Descriptor instead.
func (*BuyBookResponse) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{19}
}

func (x *BuyBookResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *BuyBookResponse) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *BuyBookResponse) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

func (x *BuyBookResponse) GetBookList() []*BuyBookInfo {
	if x != nil {
		return x.BookList
	}
	return nil
}

type BuyBookInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Isbn   string `protobuf:"bytes,1,opt,name=isbn,proto3" json:"isbn,omitempty"`
	BuyNum uint32 `protobuf:"varint,2,opt,name=buy_num,json=buyNum,proto3" json:"buy_num,omitempty"`
}

func (x *BuyBookInfo) Reset() {
	*x = BuyBookInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BuyBookInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BuyBookInfo) ProtoMessage() {}

func (x *BuyBookInfo) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BuyBookInfo.ProtoReflect.Descriptor instead.
func (*BuyBookInfo) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{20}
}

func (x *BuyBookInfo) GetIsbn() string {
	if x != nil {
		return x.Isbn
	}
	return ""
}

func (x *BuyBookInfo) GetBuyNum() uint32 {
	if x != nil {
		return x.BuyNum
	}
	return 0
}

type GetBooksByAuthorRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AuthorName string `protobuf:"bytes,1,opt,name=author_name,json=authorName,proto3" json:"author_name,omitempty"`
}

func (x *GetBooksByAuthorRequest) Reset() {
	*x = GetBooksByAuthorRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBooksByAuthorRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksByAuthorRequest) ProtoMessage() {}

func (x *GetBooksByAuthorRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksByAuthorRequest.ProtoReflect.Descriptor instead.
func (*GetBooksByAuthorRequest) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{21}
}

func (x *GetBooksByAuthorRequest) GetAuthorName() string {
	if x != nil {
		return x.AuthorName
	}
	return ""
}

type GetBooksByAuthorResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret        int32       `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ErrorInfo  string      `protobuf:"bytes,2,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
	AuthorInfo *AuthorInfo `protobuf:"bytes,3,opt,name=author_info,json=authorInfo,proto3" json:"author_info,omitempty"`
	BookInfo   []*BookInfo `protobuf:"bytes,4,rep,name=book_info,json=bookInfo,proto3" json:"book_info,omitempty"`
}

func (x *GetBooksByAuthorResponse) Reset() {
	*x = GetBooksByAuthorResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBooksByAuthorResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBooksByAuthorResponse) ProtoMessage() {}

func (x *GetBooksByAuthorResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBooksByAuthorResponse.ProtoReflect.Descriptor instead.
func (*GetBooksByAuthorResponse) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{22}
}

func (x *GetBooksByAuthorResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *GetBooksByAuthorResponse) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

func (x *GetBooksByAuthorResponse) GetAuthorInfo() *AuthorInfo {
	if x != nil {
		return x.AuthorInfo
	}
	return nil
}

func (x *GetBooksByAuthorResponse) GetBookInfo() []*BookInfo {
	if x != nil {
		return x.BookInfo
	}
	return nil
}

var File_ServiceProto_proto protoreflect.FileDescriptor

var file_ServiceProto_proto_rawDesc = []byte{
	0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0xd4,
	0x01, 0x0a, 0x08, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x69,
	0x73, 0x62, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x73, 0x62, 0x6e, 0x12,
	0x16, 0x0a, 0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1b, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07,
	0x62, 0x6f, 0x6f, 0x6b, 0x4e, 0x75, 0x6d, 0x12, 0x30, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x18, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x61, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74, 0x75,
	0x73, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x6f, 0x6f,
	0x6b, 0x54, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x42, 0x6f, 0x6f,
	0x6b, 0x54, 0x79, 0x70, 0x65, 0x22, 0x38, 0x0a, 0x0a, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x6e, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6e, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22,
	0x40, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x53, 0x42, 0x4e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x49, 0x53, 0x42, 0x4e, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x5f,
	0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x64, 0x64, 0x4e, 0x75,
	0x6d, 0x22, 0x45, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x75, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x56, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x4e,
	0x65, 0x77, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x2f, 0x0a,
	0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x12, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10,
	0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6e, 0x75, 0x6d,
	0x22, 0x45, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x44, 0x0a, 0x0f, 0x42, 0x6f, 0x6f, 0x6b, 0x53,
	0x61, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73,
	0x62, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x73, 0x62, 0x6e, 0x12, 0x1d,
	0x0a, 0x0a, 0x73, 0x65, 0x74, 0x5f, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x09, 0x73, 0x65, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0x42, 0x0a,
	0x10, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x72, 0x65, 0x74, 0x12, 0x1c, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x22, 0x3d, 0x0a, 0x0e, 0x44, 0x65, 0x63, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x53, 0x42, 0x4e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x49, 0x53, 0x42, 0x4e, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x65, 0x63, 0x5f, 0x6e,
	0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x64, 0x65, 0x63, 0x4e, 0x75, 0x6d,
	0x22, 0x42, 0x0a, 0x0f, 0x44, 0x65, 0x63, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x27, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x6f,
	0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x53, 0x42,
	0x4e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x53, 0x42, 0x4e, 0x22, 0x45, 0x0a,
	0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f,
	0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x76, 0x0a, 0x12, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65,
	0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x2f, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x42,
	0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x4c, 0x69, 0x73,
	0x74, 0x22, 0x16, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x42, 0x6f,
	0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x79, 0x0a, 0x15, 0x47, 0x65, 0x74,
	0x53, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x72, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x2f, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x27, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x4e,
	0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x62,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x73, 0x62, 0x6e, 0x22, 0x57, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x44, 0x0a, 0x0e, 0x42, 0x75, 0x79, 0x42, 0x6f, 0x6f,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x32, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x42, 0x75, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x08, 0x62, 0x6f, 0x6f, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x88, 0x01, 0x0a,
	0x0f, 0x42, 0x75, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72,
	0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52,
	0x03, 0x6e, 0x75, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x32, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x42, 0x75, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x62,
	0x6f, 0x6f, 0x6b, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x3a, 0x0a, 0x0b, 0x42, 0x75, 0x79, 0x42, 0x6f,
	0x6f, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x12, 0x0a, 0x04, 0x69, 0x73, 0x62, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x69, 0x73, 0x62, 0x6e, 0x12, 0x17, 0x0a, 0x07, 0x62, 0x75,
	0x79, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x06, 0x62, 0x75, 0x79,
	0x4e, 0x75, 0x6d, 0x22, 0x3a, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x42,
	0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1f,
	0x0a, 0x0b, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0xb3, 0x01, 0x0a, 0x18, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x42, 0x79, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x1d,
	0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x35, 0x0a,
	0x0b, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2f, 0x0a, 0x09, 0x62, 0x6f, 0x6f, 0x6b, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x62, 0x6f, 0x6f,
	0x6b, 0x49, 0x6e, 0x66, 0x6f, 0x2a, 0x29, 0x0a, 0x04, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x0a, 0x0a,
	0x06, 0x52, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x44, 0x4d,
	0x49, 0x4e, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x57, 0x4f, 0x52, 0x4b, 0x45, 0x52, 0x10, 0x02,
	0x2a, 0x26, 0x0a, 0x0e, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x61, 0x6c, 0x65, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x09, 0x0a, 0x05, 0x43, 0x4c, 0x4f, 0x53, 0x45, 0x10, 0x00, 0x12, 0x09, 0x0a,
	0x05, 0x53, 0x54, 0x41, 0x52, 0x54, 0x10, 0x01, 0x32, 0xfb, 0x02, 0x0a, 0x0c, 0x41, 0x64, 0x6d,
	0x69, 0x6e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0a, 0x41, 0x64, 0x64,
	0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x75, 0x6d, 0x12, 0x1b, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x41, 0x64, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x41, 0x0a, 0x0a, 0x44, 0x65, 0x63, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x75, 0x6d,
	0x12, 0x18, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x63, 0x42,
	0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x63, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x42,
	0x6f, 0x6f, 0x6b, 0x12, 0x1b, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x41,
	0x64, 0x64, 0x4e, 0x65, 0x77, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1c, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x4e,
	0x65, 0x77, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47,
	0x0a, 0x0a, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x1b, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x6f,
	0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x4d, 0x0a, 0x14, 0x53, 0x74, 0x61, 0x72, 0x74,
	0x4f, 0x72, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x61, 0x6c, 0x65, 0x12,
	0x19, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x53,
	0x61, 0x6c, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x42, 0x6f, 0x6f, 0x6b, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x32, 0xbc, 0x02, 0x0a, 0x0d, 0x57, 0x6f, 0x72, 0x6b, 0x65,
	0x72, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41,
	0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x1b, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x47, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x75, 0x6d, 0x12,
	0x1b, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f,
	0x6f, 0x6b, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x4e,
	0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x07, 0x42, 0x75,
	0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x18, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73,
	0x2e, 0x42, 0x75, 0x79, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x19, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x42, 0x75, 0x79, 0x42, 0x6f,
	0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x59, 0x0a, 0x10, 0x47, 0x65,
	0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x12, 0x21,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f,
	0x6b, 0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x22, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x42, 0x6f, 0x6f, 0x6b, 0x73, 0x42, 0x79, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ServiceProto_proto_rawDescOnce sync.Once
	file_ServiceProto_proto_rawDescData = file_ServiceProto_proto_rawDesc
)

func file_ServiceProto_proto_rawDescGZIP() []byte {
	file_ServiceProto_proto_rawDescOnce.Do(func() {
		file_ServiceProto_proto_rawDescData = protoimpl.X.CompressGZIP(file_ServiceProto_proto_rawDescData)
	})
	return file_ServiceProto_proto_rawDescData
}

var file_ServiceProto_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_ServiceProto_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_ServiceProto_proto_goTypes = []interface{}{
	(Role)(0),                        // 0: Services.Role
	(BookSaleStatus)(0),              // 1: Services.BookSaleStatus
	(*BookInfo)(nil),                 // 2: Services.BookInfo
	(*AuthorInfo)(nil),               // 3: Services.AuthorInfo
	(*AddBookNumRequest)(nil),        // 4: Services.AddBookNumRequest
	(*AddBookNumResponse)(nil),       // 5: Services.AddBookNumResponse
	(*AddNewBookRequest)(nil),        // 6: Services.AddNewBookRequest
	(*AddNewBookResponse)(nil),       // 7: Services.AddNewBookResponse
	(*BookSaleRequest)(nil),          // 8: Services.BookSaleRequest
	(*BookSaleResponse)(nil),         // 9: Services.BookSaleResponse
	(*DecBookRequest)(nil),           // 10: Services.DecBookRequest
	(*DecBookResponse)(nil),          // 11: Services.DecBookResponse
	(*RemoveBookRequest)(nil),        // 12: Services.RemoveBookRequest
	(*RemoveBookResponse)(nil),       // 13: Services.RemoveBookResponse
	(*GetAllBookRequest)(nil),        // 14: Services.GetAllBookRequest
	(*GetAllBookResponse)(nil),       // 15: Services.GetAllBookResponse
	(*GetSingleBookRequest)(nil),     // 16: Services.GetSingleBookRequest
	(*GetSingleBookResponse)(nil),    // 17: Services.GetSingleBookResponse
	(*GetBookNumRequest)(nil),        // 18: Services.GetBookNumRequest
	(*GetBookNumResponse)(nil),       // 19: Services.GetBookNumResponse
	(*BuyBookRequest)(nil),           // 20: Services.BuyBookRequest
	(*BuyBookResponse)(nil),          // 21: Services.BuyBookResponse
	(*BuyBookInfo)(nil),              // 22: Services.BuyBookInfo
	(*GetBooksByAuthorRequest)(nil),  // 23: Services.GetBooksByAuthorRequest
	(*GetBooksByAuthorResponse)(nil), // 24: Services.GetBooksByAuthorResponse
}
var file_ServiceProto_proto_depIdxs = []int32{
	1,  // 0: Services.BookInfo.status:type_name -> Services.BookSaleStatus
	2,  // 1: Services.AddNewBookRequest.book_info:type_name -> Services.BookInfo
	2,  // 2: Services.GetAllBookResponse.book_list:type_name -> Services.BookInfo
	2,  // 3: Services.GetSingleBookResponse.book_list:type_name -> Services.BookInfo
	22, // 4: Services.BuyBookRequest.book_list:type_name -> Services.BuyBookInfo
	22, // 5: Services.BuyBookResponse.book_list:type_name -> Services.BuyBookInfo
	3,  // 6: Services.GetBooksByAuthorResponse.author_info:type_name -> Services.AuthorInfo
	2,  // 7: Services.GetBooksByAuthorResponse.book_info:type_name -> Services.BookInfo
	4,  // 8: Services.AdminService.AddBookNum:input_type -> Services.AddBookNumRequest
	10, // 9: Services.AdminService.DecBookNum:input_type -> Services.DecBookRequest
	6,  // 10: Services.AdminService.AddNewBook:input_type -> Services.AddNewBookRequest
	12, // 11: Services.AdminService.RemoveBook:input_type -> Services.RemoveBookRequest
	8,  // 12: Services.AdminService.StartOrCloseBookSale:input_type -> Services.BookSaleRequest
	14, // 13: Services.WorkerService.GetAllBook:input_type -> Services.GetAllBookRequest
	18, // 14: Services.WorkerService.GetBookNum:input_type -> Services.GetBookNumRequest
	20, // 15: Services.WorkerService.BuyBook:input_type -> Services.BuyBookRequest
	23, // 16: Services.WorkerService.GetBooksByAuthor:input_type -> Services.GetBooksByAuthorRequest
	5,  // 17: Services.AdminService.AddBookNum:output_type -> Services.AddBookNumResponse
	11, // 18: Services.AdminService.DecBookNum:output_type -> Services.DecBookResponse
	7,  // 19: Services.AdminService.AddNewBook:output_type -> Services.AddNewBookResponse
	13, // 20: Services.AdminService.RemoveBook:output_type -> Services.RemoveBookResponse
	9,  // 21: Services.AdminService.StartOrCloseBookSale:output_type -> Services.BookSaleResponse
	15, // 22: Services.WorkerService.GetAllBook:output_type -> Services.GetAllBookResponse
	19, // 23: Services.WorkerService.GetBookNum:output_type -> Services.GetBookNumResponse
	21, // 24: Services.WorkerService.BuyBook:output_type -> Services.BuyBookResponse
	24, // 25: Services.WorkerService.GetBooksByAuthor:output_type -> Services.GetBooksByAuthorResponse
	17, // [17:26] is the sub-list for method output_type
	8,  // [8:17] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_ServiceProto_proto_init() }
func file_ServiceProto_proto_init() {
	if File_ServiceProto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ServiceProto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBookNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBookNumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNewBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNewBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookSaleRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BookSaleResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSingleBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetSingleBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookNumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BuyBookInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBooksByAuthorRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBooksByAuthorResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ServiceProto_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_ServiceProto_proto_goTypes,
		DependencyIndexes: file_ServiceProto_proto_depIdxs,
		EnumInfos:         file_ServiceProto_proto_enumTypes,
		MessageInfos:      file_ServiceProto_proto_msgTypes,
	}.Build()
	File_ServiceProto_proto = out.File
	file_ServiceProto_proto_rawDesc = nil
	file_ServiceProto_proto_goTypes = nil
	file_ServiceProto_proto_depIdxs = nil
}
