// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.19.4
// source: ServiceProto.proto

package Services

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Role int32

const (
	Role_R_NONE Role = 0
	Role_ADMIN  Role = 1
	Role_WORKER Role = 2
)

// Enum value maps for Role.
var (
	Role_name = map[int32]string{
		0: "R_NONE",
		1: "ADMIN",
		2: "WORKER",
	}
	Role_value = map[string]int32{
		"R_NONE": 0,
		"ADMIN":  1,
		"WORKER": 2,
	}
)

func (x Role) Enum() *Role {
	p := new(Role)
	*p = x
	return p
}

func (x Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Role) Descriptor() protoreflect.EnumDescriptor {
	return file_ServiceProto_proto_enumTypes[0].Descriptor()
}

func (Role) Type() protoreflect.EnumType {
	return &file_ServiceProto_proto_enumTypes[0]
}

func (x Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Role.Descriptor instead.
func (Role) EnumDescriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{0}
}

// admin 接口
// 添加书籍库存
type AddBookNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ISBN   string `protobuf:"bytes,1,opt,name=ISBN,proto3" json:"ISBN,omitempty"`
	AddNum uint64 `protobuf:"varint,2,opt,name=add_num,json=addNum,proto3" json:"add_num,omitempty"`
}

func (x *AddBookNumRequest) Reset() {
	*x = AddBookNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBookNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBookNumRequest) ProtoMessage() {}

func (x *AddBookNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBookNumRequest.ProtoReflect.Descriptor instead.
func (*AddBookNumRequest) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{0}
}

func (x *AddBookNumRequest) GetISBN() string {
	if x != nil {
		return x.ISBN
	}
	return ""
}

func (x *AddBookNumRequest) GetAddNum() uint64 {
	if x != nil {
		return x.AddNum
	}
	return 0
}

type AddBookNumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ErrorInfo string `protobuf:"bytes,2,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
}

func (x *AddBookNumResponse) Reset() {
	*x = AddBookNumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBookNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBookNumResponse) ProtoMessage() {}

func (x *AddBookNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBookNumResponse.ProtoReflect.Descriptor instead.
func (*AddBookNumResponse) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{1}
}

func (x *AddBookNumResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *AddBookNumResponse) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

// 上架新商品
type AddNewBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ISBN string `protobuf:"bytes,1,opt,name=ISBN,proto3" json:"ISBN,omitempty"`
	Num  uint64 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
}

func (x *AddNewBookRequest) Reset() {
	*x = AddNewBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNewBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewBookRequest) ProtoMessage() {}

func (x *AddNewBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewBookRequest.ProtoReflect.Descriptor instead.
func (*AddNewBookRequest) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{2}
}

func (x *AddNewBookRequest) GetISBN() string {
	if x != nil {
		return x.ISBN
	}
	return ""
}

func (x *AddNewBookRequest) GetNum() uint64 {
	if x != nil {
		return x.Num
	}
	return 0
}

type AddNewBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ErrorInfo string `protobuf:"bytes,2,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
}

func (x *AddNewBookResponse) Reset() {
	*x = AddNewBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddNewBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddNewBookResponse) ProtoMessage() {}

func (x *AddNewBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddNewBookResponse.ProtoReflect.Descriptor instead.
func (*AddNewBookResponse) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{3}
}

func (x *AddNewBookResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *AddNewBookResponse) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

// 下架商品
type DelBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ISBN string `protobuf:"bytes,1,opt,name=ISBN,proto3" json:"ISBN,omitempty"`
}

func (x *DelBookRequest) Reset() {
	*x = DelBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelBookRequest) ProtoMessage() {}

func (x *DelBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelBookRequest.ProtoReflect.Descriptor instead.
func (*DelBookRequest) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{4}
}

func (x *DelBookRequest) GetISBN() string {
	if x != nil {
		return x.ISBN
	}
	return ""
}

type DelBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ErrorInfo string `protobuf:"bytes,2,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
}

func (x *DelBookResponse) Reset() {
	*x = DelBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DelBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DelBookResponse) ProtoMessage() {}

func (x *DelBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DelBookResponse.ProtoReflect.Descriptor instead.
func (*DelBookResponse) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{5}
}

func (x *DelBookResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *DelBookResponse) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

// 减少书籍库存
type DecBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ISBN   string `protobuf:"bytes,1,opt,name=ISBN,proto3" json:"ISBN,omitempty"`
	DecNum uint64 `protobuf:"varint,2,opt,name=dec_num,json=decNum,proto3" json:"dec_num,omitempty"`
}

func (x *DecBookRequest) Reset() {
	*x = DecBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecBookRequest) ProtoMessage() {}

func (x *DecBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecBookRequest.ProtoReflect.Descriptor instead.
func (*DecBookRequest) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{6}
}

func (x *DecBookRequest) GetISBN() string {
	if x != nil {
		return x.ISBN
	}
	return ""
}

func (x *DecBookRequest) GetDecNum() uint64 {
	if x != nil {
		return x.DecNum
	}
	return 0
}

type DecBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ErrorInfo string `protobuf:"bytes,2,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
}

func (x *DecBookResponse) Reset() {
	*x = DecBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DecBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecBookResponse) ProtoMessage() {}

func (x *DecBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecBookResponse.ProtoReflect.Descriptor instead.
func (*DecBookResponse) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{7}
}

func (x *DecBookResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *DecBookResponse) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

// 删除书籍
type RemoveBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ISBN int32 `protobuf:"varint,1,opt,name=ISBN,proto3" json:"ISBN,omitempty"`
}

func (x *RemoveBookRequest) Reset() {
	*x = RemoveBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBookRequest) ProtoMessage() {}

func (x *RemoveBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBookRequest.ProtoReflect.Descriptor instead.
func (*RemoveBookRequest) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{8}
}

func (x *RemoveBookRequest) GetISBN() int32 {
	if x != nil {
		return x.ISBN
	}
	return 0
}

type RemoveBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ErrorInfo string `protobuf:"bytes,2,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
}

func (x *RemoveBookResponse) Reset() {
	*x = RemoveBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBookResponse) ProtoMessage() {}

func (x *RemoveBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBookResponse.ProtoReflect.Descriptor instead.
func (*RemoveBookResponse) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{9}
}

func (x *RemoveBookResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *RemoveBookResponse) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

// worker 接口
// 查询所有书籍数量
type GetAllBookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAllBookRequest) Reset() {
	*x = GetAllBookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllBookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBookRequest) ProtoMessage() {}

func (x *GetAllBookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBookRequest.ProtoReflect.Descriptor instead.
func (*GetAllBookRequest) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{10}
}

type GetAllBookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	ISBN      int32  `protobuf:"varint,2,opt,name=ISBN,proto3" json:"ISBN,omitempty"`
	Num       uint32 `protobuf:"varint,3,opt,name=num,proto3" json:"num,omitempty"`
	ErrorInfo string `protobuf:"bytes,4,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
}

func (x *GetAllBookResponse) Reset() {
	*x = GetAllBookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAllBookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllBookResponse) ProtoMessage() {}

func (x *GetAllBookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllBookResponse.ProtoReflect.Descriptor instead.
func (*GetAllBookResponse) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{11}
}

func (x *GetAllBookResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *GetAllBookResponse) GetISBN() int32 {
	if x != nil {
		return x.ISBN
	}
	return 0
}

func (x *GetAllBookResponse) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *GetAllBookResponse) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

// 查询数据数量
type GetBookNumRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ISBN int32 `protobuf:"varint,1,opt,name=ISBN,proto3" json:"ISBN,omitempty"`
}

func (x *GetBookNumRequest) Reset() {
	*x = GetBookNumRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookNumRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookNumRequest) ProtoMessage() {}

func (x *GetBookNumRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookNumRequest.ProtoReflect.Descriptor instead.
func (*GetBookNumRequest) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{12}
}

func (x *GetBookNumRequest) GetISBN() int32 {
	if x != nil {
		return x.ISBN
	}
	return 0
}

type GetBookNumResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Ret       int32  `protobuf:"varint,1,opt,name=ret,proto3" json:"ret,omitempty"`
	Num       uint32 `protobuf:"varint,2,opt,name=num,proto3" json:"num,omitempty"`
	ErrorInfo string `protobuf:"bytes,3,opt,name=error_info,json=errorInfo,proto3" json:"error_info,omitempty"`
}

func (x *GetBookNumResponse) Reset() {
	*x = GetBookNumResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ServiceProto_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetBookNumResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBookNumResponse) ProtoMessage() {}

func (x *GetBookNumResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ServiceProto_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBookNumResponse.ProtoReflect.Descriptor instead.
func (*GetBookNumResponse) Descriptor() ([]byte, []int) {
	return file_ServiceProto_proto_rawDescGZIP(), []int{13}
}

func (x *GetBookNumResponse) GetRet() int32 {
	if x != nil {
		return x.Ret
	}
	return 0
}

func (x *GetBookNumResponse) GetNum() uint32 {
	if x != nil {
		return x.Num
	}
	return 0
}

func (x *GetBookNumResponse) GetErrorInfo() string {
	if x != nil {
		return x.ErrorInfo
	}
	return ""
}

var File_ServiceProto_proto protoreflect.FileDescriptor

var file_ServiceProto_proto_rawDesc = []byte{
	0x0a, 0x12, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x22, 0x40,
	0x0a, 0x11, 0x41, 0x64, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x53, 0x42, 0x4e, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x49, 0x53, 0x42, 0x4e, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x5f, 0x6e,
	0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x61, 0x64, 0x64, 0x4e, 0x75, 0x6d,
	0x22, 0x45, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x75, 0x6d, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x39, 0x0a, 0x11, 0x41, 0x64, 0x64, 0x4e, 0x65,
	0x77, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x49, 0x53, 0x42, 0x4e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x53, 0x42, 0x4e,
	0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x6e,
	0x75, 0x6d, 0x22, 0x45, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x42, 0x6f, 0x6f, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72,
	0x72, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x65, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x24, 0x0a, 0x0e, 0x44, 0x65, 0x6c,
	0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x49,
	0x53, 0x42, 0x4e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x53, 0x42, 0x4e, 0x22,
	0x42, 0x0a, 0x0f, 0x44, 0x65, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x72, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x3d, 0x0a, 0x0e, 0x44, 0x65, 0x63, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x53, 0x42, 0x4e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x49, 0x53, 0x42, 0x4e, 0x12, 0x17, 0x0a, 0x07, 0x64, 0x65, 0x63,
	0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x64, 0x65, 0x63, 0x4e,
	0x75, 0x6d, 0x22, 0x42, 0x0a, 0x0f, 0x44, 0x65, 0x63, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x27, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65,
	0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x49,
	0x53, 0x42, 0x4e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x49, 0x53, 0x42, 0x4e, 0x22,
	0x45, 0x0a, 0x12, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x13, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x6b, 0x0a, 0x12, 0x47,
	0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03,
	0x72, 0x65, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x49, 0x53, 0x42, 0x4e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x49, 0x53, 0x42, 0x4e, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x27, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x42,
	0x6f, 0x6f, 0x6b, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a,
	0x04, 0x49, 0x53, 0x42, 0x4e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x49, 0x53, 0x42,
	0x4e, 0x22, 0x57, 0x0a, 0x12, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x75, 0x6d, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x72, 0x65, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x72, 0x65, 0x74, 0x12, 0x10, 0x0a, 0x03, 0x6e, 0x75, 0x6d,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x03, 0x6e, 0x75, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x65,
	0x72, 0x72, 0x6f, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2a, 0x29, 0x0a, 0x04, 0x52, 0x6f,
	0x6c, 0x65, 0x12, 0x0a, 0x0a, 0x06, 0x52, 0x5f, 0x4e, 0x4f, 0x4e, 0x45, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x41, 0x44, 0x4d, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x57, 0x4f, 0x52,
	0x4b, 0x45, 0x52, 0x10, 0x02, 0x32, 0xec, 0x02, 0x0a, 0x0c, 0x41, 0x64, 0x6d, 0x69, 0x6e, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x47, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x42, 0x6f, 0x6f,
	0x6b, 0x4e, 0x75, 0x6d, 0x12, 0x1b, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x41, 0x64, 0x64, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64,
	0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12,
	0x41, 0x0a, 0x0a, 0x44, 0x65, 0x63, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x75, 0x6d, 0x12, 0x18, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x63, 0x42, 0x6f, 0x6f, 0x6b,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x19, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63,
	0x65, 0x73, 0x2e, 0x44, 0x65, 0x63, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x47, 0x0a, 0x0a, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x42, 0x6f, 0x6f, 0x6b,
	0x12, 0x1b, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x4e,
	0x65, 0x77, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e,
	0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x41, 0x64, 0x64, 0x4e, 0x65, 0x77, 0x42,
	0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3e, 0x0a, 0x07, 0x44,
	0x65, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x18, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x44, 0x65, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x19, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x44, 0x65, 0x6c, 0x42,
	0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x47, 0x0a, 0x0a, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x1b, 0x2e, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x73, 0x2e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x32, 0xa5, 0x01, 0x0a, 0x0d, 0x57, 0x6f, 0x72, 0x6b, 0x65, 0x72, 0x53,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x4b, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c,
	0x42, 0x6f, 0x6f, 0x6b, 0x12, 0x1b, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e,
	0x47, 0x65, 0x74, 0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1c, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x6c, 0x6c, 0x42, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x28,
	0x01, 0x30, 0x01, 0x12, 0x47, 0x0a, 0x0a, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x75,
	0x6d, 0x12, 0x1b, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74,
	0x42, 0x6f, 0x6f, 0x6b, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1c,
	0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2e, 0x47, 0x65, 0x74, 0x42, 0x6f, 0x6f,
	0x6b, 0x4e, 0x75, 0x6d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x0c, 0x5a, 0x0a,
	0x2e, 0x2f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_ServiceProto_proto_rawDescOnce sync.Once
	file_ServiceProto_proto_rawDescData = file_ServiceProto_proto_rawDesc
)

func file_ServiceProto_proto_rawDescGZIP() []byte {
	file_ServiceProto_proto_rawDescOnce.Do(func() {
		file_ServiceProto_proto_rawDescData = protoimpl.X.CompressGZIP(file_ServiceProto_proto_rawDescData)
	})
	return file_ServiceProto_proto_rawDescData
}

var file_ServiceProto_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_ServiceProto_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_ServiceProto_proto_goTypes = []interface{}{
	(Role)(0),                  // 0: Services.Role
	(*AddBookNumRequest)(nil),  // 1: Services.AddBookNumRequest
	(*AddBookNumResponse)(nil), // 2: Services.AddBookNumResponse
	(*AddNewBookRequest)(nil),  // 3: Services.AddNewBookRequest
	(*AddNewBookResponse)(nil), // 4: Services.AddNewBookResponse
	(*DelBookRequest)(nil),     // 5: Services.DelBookRequest
	(*DelBookResponse)(nil),    // 6: Services.DelBookResponse
	(*DecBookRequest)(nil),     // 7: Services.DecBookRequest
	(*DecBookResponse)(nil),    // 8: Services.DecBookResponse
	(*RemoveBookRequest)(nil),  // 9: Services.RemoveBookRequest
	(*RemoveBookResponse)(nil), // 10: Services.RemoveBookResponse
	(*GetAllBookRequest)(nil),  // 11: Services.GetAllBookRequest
	(*GetAllBookResponse)(nil), // 12: Services.GetAllBookResponse
	(*GetBookNumRequest)(nil),  // 13: Services.GetBookNumRequest
	(*GetBookNumResponse)(nil), // 14: Services.GetBookNumResponse
}
var file_ServiceProto_proto_depIdxs = []int32{
	1,  // 0: Services.AdminService.AddBookNum:input_type -> Services.AddBookNumRequest
	7,  // 1: Services.AdminService.DecBookNum:input_type -> Services.DecBookRequest
	3,  // 2: Services.AdminService.AddNewBook:input_type -> Services.AddNewBookRequest
	5,  // 3: Services.AdminService.DelBook:input_type -> Services.DelBookRequest
	9,  // 4: Services.AdminService.RemoveBook:input_type -> Services.RemoveBookRequest
	11, // 5: Services.WorkerService.GetAllBook:input_type -> Services.GetAllBookRequest
	13, // 6: Services.WorkerService.GetBookNum:input_type -> Services.GetBookNumRequest
	2,  // 7: Services.AdminService.AddBookNum:output_type -> Services.AddBookNumResponse
	8,  // 8: Services.AdminService.DecBookNum:output_type -> Services.DecBookResponse
	4,  // 9: Services.AdminService.AddNewBook:output_type -> Services.AddNewBookResponse
	6,  // 10: Services.AdminService.DelBook:output_type -> Services.DelBookResponse
	10, // 11: Services.AdminService.RemoveBook:output_type -> Services.RemoveBookResponse
	12, // 12: Services.WorkerService.GetAllBook:output_type -> Services.GetAllBookResponse
	14, // 13: Services.WorkerService.GetBookNum:output_type -> Services.GetBookNumResponse
	7,  // [7:14] is the sub-list for method output_type
	0,  // [0:7] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_ServiceProto_proto_init() }
func file_ServiceProto_proto_init() {
	if File_ServiceProto_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ServiceProto_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBookNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBookNumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNewBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddNewBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DelBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DecBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllBookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAllBookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookNumRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_ServiceProto_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetBookNumResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ServiceProto_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_ServiceProto_proto_goTypes,
		DependencyIndexes: file_ServiceProto_proto_depIdxs,
		EnumInfos:         file_ServiceProto_proto_enumTypes,
		MessageInfos:      file_ServiceProto_proto_msgTypes,
	}.Build()
	File_ServiceProto_proto = out.File
	file_ServiceProto_proto_rawDesc = nil
	file_ServiceProto_proto_goTypes = nil
	file_ServiceProto_proto_depIdxs = nil
}
